---

- name: Assertion
  ansible.builtin.assert:
    that:
      - sysctl_settings != {}

- name: Create custom locations
  ansible.builtin.file:
    path: /etc/sysctl.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Check for status of /etc/sysctl.conf
  ansible.builtin.stat:
    path: /etc/sysctl.conf
  register: __sysctl_conf

- name: Disable same settings in /etc/sysctl.conf
  ansible.builtin.replace:
    path: /etc/sysctl.conf
    regexp: "^\\s*({{ item.key }})\\s*=\\s*(.*)"
    replace: "# \\1 = \\2"
  loop: "{{ sysctl_settings | dict2items }}"
  when: __sysctl_conf.stat.exists

- name: Set persistant settings
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-overwrite.conf
    reload: true
  loop: "{{ sysctl_settings | dict2items }}"
