---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    molecule_driver: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') }}"
    sysctl_settings: {'net.ipv4.conf.default.rp_filter': '1', 'net.ipv4.ip_forward': '1', 'net.ipv4.ip_nonlocal_bind': '1'}
  tasks:
    - name: Include role 'ansible-role-sysctl'
      ansible.builtin.include_role:
        name: ansible-role-sysctl
